print ("hello")
x = input ("How are you:")
print (x)
print ("at this time we will know something more personal about you")
name = input ("Please type your favorite color:")
print (name)
print ("Also Your favorite color is")
print (name)
print ("thank you for participating")
print ("Have a nice day")
print ("Bye")